version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=db_root_passwd
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pdb_root_passwd"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  redis:
    image: redis:7
    container_name: seadoc-redis
    restart: unless-stopped
    volumes:
      - ./seadoc-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - seafile-net

  seafile:
    image: docker.io/seafileltd/seafile-mc:13.0.0
    container_name: seafile
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./seafile-data:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_root_passwd
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=192.168.x.x   # change to your Mac’s LAN IP
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - seafile-net

  seadoc:
    image: docker.io/seafileltd/seadoc-server:0.5
    container_name: seadoc
    restart: unless-stopped
    environment:
      - SEADOC_SERVER_HOSTNAME=192.168.x.x   # LAN IP
      - SEADOC_SERVER_PORT=8081
    ports:
      - "8081:80"
    volumes:
      - ./seadoc-data:/var/lib/seadoc
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - seafile-net

networks:
  seafile-net:
