version: "3.9"

services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_root_passwd
    command:
      [
        "--transaction-isolation=READ-COMMITTED",
        "--binlog-format=ROW",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci"
      ]
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - seafile-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pdb_root_passwd"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
    restart: unless-stopped

  seafile:
    image: docker.io/seafileltd/seafile-mc:13.0.8
    container_name: seafile
    user: "0:0"
    ports:
      - "8080:80"
    volumes:
      - ./seafile-data:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_root_passwd
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=localhost
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - seafile-net
    restart: unless-stopped

networks:
  seafile-net:
    name: seafile-net
